signupbetter/website/src/app/models/signups.py
import datetime
from typing import List

from sqlalchemy.orm import Mapped, mapped_column
from app.extensions import db
from app.models.auth import User
from app.signups.create_signup import InvalidDayError, SignupType, SignupSortingMethod, CommentingStatus

class SignupSlot(db.Model):
    __tablename__ = 'signup_slot'
    
    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(db.String(50))
    location: Mapped[str] = mapped_column(db.String(50))
    details: Mapped[str] = mapped_column(db.String(200))
    time: Mapped[datetime.time] = mapped_column()  # Stored in HH:MM:SS format
    date: Mapped[datetime.date] = mapped_column()  # Stored in YYYY-MM-DD format
    day: Mapped[str] = mapped_column(db.String(10))
    signUpLimit: Mapped[int] = mapped_column(db.SmallInteger())
    
    signup_id: Mapped[int] = mapped_column(db.Integer, db.ForeignKey('signup.id'))
    signup: Mapped['Signup'] = db.relationship(back_populates='slots')
    users: Mapped[List['User']] = db.relationship(secondary='signup_slot_user', back_populates='signed_up_slots')
    
    def __init__(self, name: str, signUpLimit: int, details: str, location: str, time: datetime.time, date: datetime.date, day: str):                
        self.name = name
        self.details = details
        self.location = location
        self.time = time
        self.signUpLimit = signUpLimit
        self.date = date
        self.set_day(day)
    
    def signUp(self, user: User):
        if self.signUpLimit > 0 and len(self.users) >= self.signUpLimit:
            raise ValueError("Sign-up limit reached for this slot.")
        self.users.append(user)
        db.session.commit()

signup_slot_user = db.Table('signup_slot_user',
    db.Column('signup_slot_id', db.Integer, db.ForeignKey('signup_slot.id'), primary_key=True),
    db.Column('user_id', db.Integer, db.ForeignKey('user.id'), primary_key=True)
)


class Signup(db.Model):
    __tablename__ = 'signup'
    
    id: Mapped[int] = mapped_column(primary_key=True)
    signUpType: Mapped[int]
    name: Mapped[str] = mapped_column(db.String(50))
    details: Mapped[str] = mapped_column(db.String(200))
    can_cancel: Mapped[bool] = mapped_column(default=False) 
    commenting_status: Mapped[int] = mapped_column(db.SmallInteger())
    published: Mapped[bool] = mapped_column(default=False)
    sorting_method: Mapped[int] = mapped_column(db.SmallInteger())

    owner_id: Mapped[int] = mapped_column(db.Integer, db.ForeignKey('user.id'))
    owner: Mapped['User'] = db.relationship(back_populates='signups')
    slots: Mapped[List['SignupSlot']] = db.relationship(back_populates='signup')

    def __init__(self, owner: User, name: str, details: str, signUpType: SignupType, canCancel: bool, commenting_status: CommentingStatus, published: bool, sorting_method: SignupSortingMethod):
        if signUpType not in SignupType:
            raise ValueError("Invalid sign up type")
        if sorting_method not in SignupSortingMethod:
            raise ValueError("Invalid sorting method")
        if commenting_status not in CommentingStatus:
            raise ValueError("Invalid option for comments")
        
        self.owner = owner
        self.name = name
        self.details = details
        self.signUpType = signUpType.value
        self.canCancel = canCancel
        self.commenting_status = commenting_status.value
        self.published = published
        self.sorting_method = sorting_method.value

    def add_slot(self, slot: SignupSlot):
        if self.signUpType == SignupType.SCHEDULING and (slot.time is None or slot.date is None or slot.day is None):
            raise ValueError("No date, day, or time was passed in.")
        elif self.signUpType == SignupType.PROJECT and slot.name is None:
            raise ValueError("No name was passed in")
        
        self.slots.append(slot)
        slot.signup_id = self.id  # Set the signup_id to link the slot to this signup
        db.session.add(slot)
        db.session.commit()
    
    def set_day(self, day):
        valid_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
        if day.capitalize() not in valid_days:
            raise InvalidDayError(f"'{day}' is not a valid day.")
        self.day = day.capitalize()

signupbetter/website/src/app/signups/__init__.py
from flask import Blueprint

bp = Blueprint('signups', __name__)


from app.signups import routes

signupbetter/website/src/app/signups/routes.py
import datetime
from flask import render_template, redirect, request, url_for, flash
from flask_login import current_user, login_required
from app.extensions import db
from app.signups import bp
from app.signups.create_signup import InvalidDayError, SignupType, CommentingStatus, SignupSortingMethod
from app.models.signups import SignupSlot, Signup

@bp.route('/create-a-signup/', methods=['GET', 'POST'])
@login_required
def create_new_signup():
    if request.method == 'GET':
        return render_template(
            'signups/new_signup.html',
        )
    
    published: bool = request.form.get('published', 'false').lower() == 'true'
    signup_name: str = request.form.get('signup_name')
    signup_details: str = request.form.get('signup_details')
    try:
        signup_type: SignupType = SignupType.fromStr(request.form.get('signup_type'))
    except ValueError:
        flash('Invalid sign up type.', 'error')
        return render_template('signups/new_signup.html')
    can_cancel: bool = request.form.get('can_cancel', 'false').lower() == 'true'
    try:
        commenting_status: CommentingStatus = CommentingStatus.fromStr(request.form.get('commenting_status'))
    except ValueError:
        flash('Invalid option chosen for commenting in settings.', 'error')
        return render_template('signups/new_signup.html')
    try:
        sorting_method: SignupSortingMethod = SignupSortingMethod.fromStr(request.form.get('sorting_method'))
    except ValueError:
        flash('Invalid sorting method chosen in settings.', 'error')
        return render_template('signups/new_signup.html')
    
    try:
        new_signup = Signup(
            owner=current_user,
            name=signup_name,
            details=signup_details,
            signUpType=signup_type,
            canCancel=can_cancel,
            commenting_status=commenting_status,
            sorting_method=sorting_method,
            published=published
        )

        db.session.add(new_signup)
        db.session.commit()
        db.session.flush()  # Flush to get the ID of the new_signup before adding slots
        
        slot_ids = [key for key in request.form.keys() if key.startswith('slot-')]
        for slot_id in slot_ids:
            location = request.form.get(f'{slot_id}-location')
            amt = request.form.get(f'{slot_id}-amt')
            details = request.form.get(f'{slot_id}-details')
            date = request.form.get(f'{slot_id}-date')
            day = request.form.get(f'{slot_id}-day')
            time = request.form.get(f'{slot_id}-time')

            # Create and add new Slot objects
            new_slot = SignupSlot(
                signup_id=new_signup.id,
                location=location,
                signUpLimit=int(amt) if amt else 0,
                details=details,
                date=datetime.datetime.strptime(date, '%Y-%m-%d').date() if date else None,
                day=day,
                time=datetime.datetime.strptime(time, '%H:%M').time() if time else None
            )
            db.session.add(new_slot)
            new_signup.add_slot(new_slot)
        db.session.commit()
        
        flash('Signup created successfully!', 'success')
        return redirect(url_for('signups.view_signup', signup_id=new_signup.id))
    except InvalidDayError as e:
        flash('You somehow managed to pass in an invalid day.', 'error')
    except ValueError as e:
        flash(str(e), 'error')
    except Exception as e:
        print(e)
        flash('An unexpected error occurred. Please try again.', 'error')
        db.session.rollback()

    return render_template('signups/new_signup.html')


@bp.route('/view-signup/<int:signup_id>', methods=['GET'])
@login_required
def view_signup(signup_id):
    signup = Signup.query.get_or_404(signup_id)
    signup_slots = SignupSlot.query.filter_by(signup_id=signup.id).all()
    
    return render_template(
        'signups/view_signup.html',
        signup=signup,
        signup_slots=signup_slots
    )

signupbetter/website/src/app/templates/signups/new_signup.html
{% extends 'base.html' %}

{% block title %}Register for SignUpBetter{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/signups.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="centered-page">
    <h1>New Signup</h1>

    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
        <div class="alert alert-danger">
            <ul>
                {%- for msg in errors %}
                    <li>{{ msg }}</li>
                {% endfor -%}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% endwith %}

    {% with successes = get_flashed_messages(category_filter=["success"]) %}
    {% if successes %}
        <div class="alert alert-success">
            <ul>
                {%- for msg in errors %}
                    <li>{{ msg }}</li>
                {% endfor -%}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% endwith %}
    
    <ul class="nav nav-tabs" id="new_signup_tabs" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link disabled" id="general-info-tab" data-bs-toggle="tab" data-bs-target="#general-info" type="button" role="tab" aria-controls="general-info" aria-selected="true">General Info</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link disabled" id="slots-tab" data-bs-toggle="tab" data-bs-target="#slots" type="button" role="tab" aria-controls="slots" aria-selected="false">Slots</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link disabled" id="settings-tab" data-bs-toggle="tab" data-bs-target="#settings" type="button" role="tab" aria-controls="settings" aria-selected="false">Settings</button>
        </li>
    </ul>

    <form method="POST" action="{{ url_for('signups.create_new_signup') }}" class="create-new-signup">
        <div class="tab-content">
            <div class="tab-pane fade show active" id="general-info" role="tabpanel" aria-labelledby="general-info-tab">
                <label for="signup_name" required>Name of the Signup: </label>
                <input class="form-control" type="text" name="signup_name" placeholder="Your Signup" autofocus="" id="signup_name" aria-required="true" required>

                <br>

                <label for="signup_details" required>Details about the Signup: </label>
                <textarea maxlength="200" class="form-control" type="text" name="signup_details" placeholder="Details" id="signup_details" aria-required="true" required></textarea>

                <br>
                
                <label for="signup_slot_amt_default" required>
                    How many people can sign up for each slot?
                    <span data-bs-toggle="tooltip" data-bs-placement="right" title="Set this to zero if you want infinite people to be able to sign up.">
                        <i class="bi bi-question-circle"></i>
                    </span>
                </label>
                <input type="number" name="signup_slot_amt_default" id="signup_slot_amt_default" class="form-control" value="5" min="0" max="100">

                <br>


                <label for="signup_type" required>What will this signup be used for? </label>
                <div>
                    <div class="signup-type-radiobutton">
                        <div class="form-check signup-type-radiobutton-content">
                            <input class="form-check-input" type="radio" name="signup_type" id="signup_type_scheduling" checked value="scheduling">
                            <label class="form-check-label" for="signup_type_scheduling">
                                Scheduling Appointments
                            </label>
                            <span data-bs-toggle="tooltip" data-bs-placement="right" title="Use this option if you want people to be able to choose a specific timeslot to do something.">
                                <i class="bi bi-question-circle"></i>
                            </span>
                        </div>
                    </div>
                    <div class="signup-type-radiobutton">
                        <div class="form-check signup-type-radiobutton-content">
                            <input class="form-check-input" type="radio" name="signup_type" id="signup_type_projects" value="projects">
                            <label class="form-check-label" for="signup_type_projects">
                                Projects
                            </label>
                            <span data-bs-toggle="tooltip" data-bs-placement="right" title="Use this option if you want people to be able to sign up for a project.">
                                <i class="bi bi-question-circle"></i>
                            </span>
                        </div>
                    </div>
                </div>

                <button type="button" class="btn btn-secondary signup-fake-next-button">
                    Next
                    <i class="bi bi-arrow-right-circle"></i>
                </button>
                <button type="button" class="btn btn-warning edit-later">
                    Save and Edit Later
                </button>
            </div>

            <div class="tab-pane fade" id="slots" role="tabpanel" aria-labelledby="slots-tab">
                <h2>Slots</h2>

                <div class="slots-div"></div>
                
                <br />
                
                <button type="button" class="btn btn-secondary add-slot-btn">
                    Add Slot
                    <i class="bi bi-plus"></i>
                </button>
                
                <br />
                
                <button type="button" class="btn btn-secondary signup-back-btn disabled" disabled>
                    Back
                    <i class="bi bi-arrow-left-circle"></i>
                </button>
                <button type="button" class="btn btn-primary signup-next-btn">
                    Next
                    <i class="bi bi-arrow-right-circle"></i>
                </button>
                <button type="button" class="btn btn-warning edit-later">
                    Save and Edit Later
                </button>
            </div>

            <div class="tab-pane fade" id="settings" role="tabpanel" aria-labelledby="settings-tab">
                <h2>Settings</h2>
                
                <label for="unsignups">Can people cancel after signing up?</label>
                <input type="checkbox" name="can_cancel" id="can_cancel" class="form-check-input">

                <br>
                
                <label for="commenting_status">Comments</label>
                <select name="commenting_status" id="commenting_status" class="form-select" aria-label="Commenting status">
                    <option value="required">Required</option>
                    <option selected value="optional">Optional</option>
                    <option value="disabled">Disabled</option>
                </select>
                <br>

                <label for="sorting_method">How would you like for the slots to be sorted?</label>
                <select name="sorting_method" id="sorting_method" class="form-select">
                    <!-- OPTIONS POPULATED USING JS -->
                </select>

                <br>
                
                <button type="button" class="btn btn-secondary signup-back-btn">
                    Back
                    <i class="bi bi-arrow-left-circle"></i>
                </button>
                <button type="submit" class="btn btn-primary btn-lg">
                    Create Signup!
                </button>
                <button type="submit" class="btn btn-warning edit-later">
                    Save and Edit Later
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block modals %}
    <!-- Modal to lock the signup type -->
    <div class="modal fade" id="lockSignupType" tabindex="-1" role="dialog" aria-labelledby="promptLockSignupType" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="promptLockSignupType">Are you sure you wish to continue?</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Once you continue, you cannot change the type of signup that this is.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary signup-next-btn" data-bs-dismiss="modal">Continue</button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">I need to make changes!</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block js %}
<script src="{{ url_for('static', filename='js/new_signup.js') }}"></script>
{% endblock %}

signupbetter/website/src/app/templates/signups/view_signup.html
{% extends 'base.html' %}

{% block title %}Register for SignUpBetter{% endblock %}

{% block head %}
<link href="{{ url_for('static', filename='css/signups.css') }}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="wrapper">
    {% with errors = get_flashed_messages(category_filter=["error"]) %}
    {% if errors %}
    <div class="alert alert-danger">
        <ul>
            {%- for msg in errors %}
            <li>{{ msg }}</li>
            {% endfor -%}
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endwith %}
    
    {% with successes = get_flashed_messages(category_filter=["success"]) %}
    {% if successes %}
    <div class="alert alert-success">
            <ul>
                {%- for msg in successes %}
                    <li>{{ msg }}</li>
                    {% endfor -%}
                </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}
    {% endwith %}

    <h1>{{ signup.name }}</h1>
    <p>{{ signup.details }}</p>
    
</div>
{% endblock %}

{% block modals %}

{% endblock %}


{% block js %}

{% endblock %}